PATHS:
    dist:
        folder:
            - 'dist'
        css:
            - 'dist/css'
        javascript:
            - 'dist/js'
        images:
            - 'dist/img'
    src:
        folder:
            - 'src'
        sass:
            - 'src/assets/scss'
        javascript:
            - 'src/assets/js'
        javascriptEntries:
            - 'src/assets/js/app.js'
        images:
            - 'src/assets/img'
        staticAssets:
            - 'src/assets/*vendor/**/*'
        templates:
            pages:
                - 'src/pages'
            layouts:
                - 'src/layouts'
            partials:
                - 'src/partials'
            data:
                - 'src/data'
            helpers:
                - 'src/helpers'
    inlcudePathsForSass:
        - 'node_modules'
    clean: 'dist/**/*'

BROWSERSYNC:
    port: 8000
    scrollmode: false
