PATHS:
    dist:
        folder:
            - 'dist'
        css:
            - 'dist/css'
        javascript:
            - 'dist/js'
        images:
            - 'dist/img'
    src:
        folder:
            - 'src'
        css:
            - 'src/assets/css'
        javascript:
            - 'src/assets/js'
        javascriptEntries:
            - 'src/assets/js/app.js'
        images:
            - 'src/assets/img'
        staticAssets:
            - 'src/assets/*vendor/**/*'
            - 'src/assets/img/favicon.ico'
        templates:
            - 'src/templates'
    clean: 'dist/**/*'

BROWSERSYNC:
    port: 8000
    scrollmode: false
